name: Deploy and Build on EC2

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. SSH 설정 및 Git Pull
      - name: Deploy and restart application on EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }} # GitHub Secrets에 등록한 SSH 개인키
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 43.203.90.24 >> ~/.ssh/known_hosts
          ssh -o StrictHostKeyChecking=no ec2-user@43.203.90.24 << 'EOF'
            # 프로젝트 디렉토리로 이동
            cd /home/ec2-user/morethandaily

            # 기존 프로세스 종료 (포트를 사용하는 프로세스 찾기 및 종료)
            echo "Checking for existing processes on port 8080..."
            PID=$(lsof -ti:8080)
            if [ -n "$PID" ]; then
              echo "Killing process $PID..."
              kill -9 $PID
            else
              echo "No process running on port 8080."
            fi

            # 최신 코드 가져오기
            git pull origin main

            # Gradle 빌드 실행
            ./gradlew build

            # 새 애플리케이션 실행
            nohup java -jar build/libs/morethandaily-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
          EOF
